### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [jridley11/prj-rev-bwfs-dasmoto#1]
Grade: Satisfactory

Great job on your project - I loved how you were able to incorporate the `<p>` and `<h2>`  tag making your HTML very neat! In addition to this, you utilized the `<span>` tag properly where you incorporated the blue font color. These two aspects of your code helped you meet the design requirements! An area for improvement here is with respect to your other implementation of the class attribute. For your headings you should have opted for `id` instead.

A recommendation here is to review the following article. Try applying the concept and its usage. It will aid you as your projects get more complex. Read it thoroughly and view the examples! Keep up the great work!
[id vs. class](https://css-tricks.com/the-difference-between-id-and-class/)

**Comment by jridley11** [comment]
Thanks Gabriel! I appreciate your reviewing of my project and for the constructive feedback in areas for me to improve. Thank you also for attaching the article. I has helped me understand more of the differences in the use of classes vs ids. After reading, I've since gone back and applied the ids to the project and can now see how this is the more appropriate choice.

I have one question which I've added under issue#3 but will also add here regarding the alt attribute. Could you please explain a little more regarding this as I have reviewed the notes regarding images (section 8 of the HTML Tags lesson) and can't find anything regarding the alt attribute? It only mentions the following:

"The  tag has a required attribute called src. The src attribute must be set to the image's source, or the location of the image."

Best regards,
Jonathan

**Comment by gdedi001** [comment]
Sure, check out this documentation. This attribute is to show detail even when the page is slow to load or if they are using software for disability purposes.
https://www.w3schools.com/TAGs/att_img_alt.asp

**Comment by jridley11** [comment]
That's great. Many thanks again Gabriel for your help and feedback.

Best regards,
Jonathan
